# Generated by Django 2.2.3 on 2019-07-12 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('financeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_no', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('is_company', models.BooleanField()),
                ('price_type', models.CharField(choices=[('R', 'Retail'), ('W', 'Wholesale'), ('D', 'Dealer'), ('S', 'Special')], default='R', max_length=2)),
                ('unit_number', models.CharField(blank=True, max_length=50, verbose_name='House/Appt No')),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('vat_registration_number', models.IntegerField(blank=True, default=0)),
                ('business_registration_number', models.CharField(blank=True, max_length=9)),
                ('discount_percent', models.FloatField(blank=True, default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 7, 12, 13, 43, 41, 449098, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 7, 12, 13, 43, 41, 449098, tzinfo=utc))),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('bills', 'Bills'), ('Payments', 'payments'), ('pettycash', 'Pettycash'), ('other', 'Other')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('requisition_number', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 7, 12, 13, 43, 41, 450098, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 7, 12, 13, 43, 41, 450098, tzinfo=utc))),
                ('Amount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeApp.Customer')),
            ],
        ),
    ]
